project:
  type: website
  output-dir: docs

website:
  title: "colleenmccamy.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - projects.qmd
      - resume.qmd

format:
  html:
    theme: 
      - customized_styles.scss
    mainfont: Montserrat
    toc: true

editor: visual

