project:
  type: website
  output-dir: docs

website:
  favicon: images/logo_cm.png
  title: "Colleen McCamy"
  page-footer:
    left: 
      - icon: github
        href: https://github.com/colleenmccamy
      - icon: linkedin
        href: https://www.linkedin.com/in/colleen-mccamy/
    right: "Copyright 2022, Colleen McCamy"
    border: false
    background: light
  navbar:
    title: false
    logo: images/logo_cm.png
    right:
      - about.qmd
      - blog.qmd
      - icon: code-square
        href: projects.qmd
        #icon: code-square
      #- resume.qmd
    collapse-below: sm
    search: true

format:
  html:
    theme: 
      - customized_styles.scss
    mainfont: Montserrat
    toc: true

editor: visual

