project:
  type: website
  output-dir: docs

website:
  favicon: images/logo_cm.png
  navbar:
    title: false
    logo: images/logo_cm.png
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - blog.qmd
      - projects.qmd
      - resume.qmd

format:
  html:
    theme: 
      - customized_styles.scss
    mainfont: Montserrat
    toc: true

editor: visual

