---
title: "About"
---


Colleen is a self-proclaimed energy nerd passionate about the intersection of climate, creativity and community.

Colleen received a Bachelor of Arts in Environmental Studies at the University of California, Santa Barbara and held many jobs which helped her navigate the wide range of paths within the environmental field -- such as working at a research lab focused on kelp forest ecosystems, at a UC Natural Reserve in the Eastern Sierra Nevada's, and with hands-on environmental education.

However, it was her fellowship with the UC Carbon Neutrality Initiative that introduced her to the world of clean energy and the impact she can make in the field. After graduating, Colleen followed her interest and joined the community choice energy agency, Silicon Valley Clean Energy. In her role, she managed and developed digital tools to help communities electrify and take advantage of their local, clean electricity.

Currently, Colleen is pursuing a Master in Environmental Data Science at the Bren School of Environmental Science and Management and is excited to unlock data science skills and dive deeper into clean energy questions with a data lens. Colleen aims to build creative data visualizations that connect communities to energy insights and help guide policies, encourage action, and amplify equitable solutions.
